service: ProjectAWS
frameworkVersion: "2 || 3"

provider:
  name: aws
  runtime: nodejs14.x
  region: "us-east-1"
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-east-1:523353628067:table/RegAnimal

functions:
  addAnimals:
    handler: handler.addAnimals
    events:
      - httpApi:
          path: /addAnimals
          method: post

  getAnimals:
    handler: handler.getAnimals
    events:
      - httpApi:
          path: /getAnimals
          method: get
          
  getQuery:
    handler: handler.getQuery
    events:
      - httpApi:
          path: /getQuery
          method: post

  updateAnimals:
    handler: handler.updateAnimals
    events:
      - httpApi:
          path: /updateAnimals
          method: post

resources:
  Resources:
    RegAnimal:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: RegAnimal
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
